# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Blog
tagline:          'RAD301 MVC App'
description:      'A multi-branch worked example of ASP.NET MVC. Made by <a href="http://jkelleher.me" target="_blank">J Kelleher</a>.'
url:              http://itsligo.github.io/blog/
baseurl:          http://itsligo.github.io/blog/

author:
  name:           'John Kelleher'
  url:            http://jkelleher.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/itsligo/blog
